# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab3bc9a9cce5dc0f2d939c89584779629ba82867067af12a60e235897bc4672ff836d597f7fd9712696fd9add7ec50405b2a1db5e8e0c2ef2d7934d3b2091843

test:
  secret_key_base: 072af7e77d0e581941df984ac86686d34c20a5783fb71c47e58c7b070c2620b05e2bfa9b199140773715af2fcf9a9b684e6f255c9cb826abb232ae10f2829588

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
